services:
  sekhmet:
    container_name: sekhmet_app
    build:
      context: ../
      dockerfile: ./docker/sekhmet/Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./sekhmet.env
        required: true
    ports:
      - ${PORT}:4500
    networks:
      - dev_room
    environment:
      TOKEN: ${TOKEN}
      EMBED: ${EMBED}
